### ISSUE TITLE
[FEATURE] Support for Inverter POW-HVM4.2M-24V support

### ISSUE THREAD

**Issue by sparky-dog** [softwarecrash/Solar2MQTT-ESP8266#102]
### Is your feature request related to a problem? Please describe

the device can connect to the MQTT server but the DeviceData and LiveData are empty
```
 mosquitto_sub -t "#"
true
192.168.1.32
{"EspData":{"Device_name":"POW-HVM4.2M-24V","ESP_VCC":3.036,"Wifi_RSSI":-71,"sw_version":"1.1.7","Free_Heap":24272,"HEAP_Fragmentation":41,"json_memory_usage":377,"json_capacity":2048,"runtime":358,"ws_clients":0,"detect_protocol":0},"DeviceData":{},"LiveData":{}}
true
-71
```

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by softwarecrash** [comment]
Support your device the PC Software watchpower or Solarpower?
