### ISSUE TITLE
Powmr 1.6kw not working in wemos and no data i hope this fix a soon

### ISSUE THREAD

**Issue by Ching858** [softwarecrash/Solar2MQTT-ESP8266#104]
### What device are you using?

Powmr 1.6kw not working I can't access the data.. I hope my problem will fix soon. Please see the attached file.
Thank you
![Screenshot_20240805-150946_Chrome](https://github.com/user-attachments/assets/7519d39c-2256-400f-93fc-ed8f6e8ba16a)

**Comment by derLoosi** [comment]
Does your device work using the Watchpower PC Software? 
Also i think we need a picture of your wiring.

I cant see Powmr 1.6kw on the [Confirmed Working Device List](https://github.com/softwarecrash/Solar2MQTT/wiki/Confirmed-Working-Device-List)

**Comment by hvdb** [comment]
I have the same one.
Although it's rated as 1.6kw

Type is pow-hvm2.0h-12v

Doesn't work for me as well, can t find the controller it seems

I think I have it wired correctly

![IMG_7466](https://github.com/user-attachments/assets/e9398b8f-257d-4696-ac41-c069a3522d92)
![IMG_7467](https://github.com/user-attachments/assets/e842342d-d371-46ab-89da-c58af3153ee6)
![IMG_7468](https://github.com/user-attachments/assets/d6aa809a-b230-4762-b53b-00ea2201b226)

**Comment by softwarecrash** [comment]
Again...
Please Check if the device Work with the PC Software watchpower or Solarpower, when this will Work, the ESP Firmware will Work too.
Actual only the communication from this sowares are supported.

**Comment by Ching858** [comment]
What is watch power or solarpower

**Comment by Ching858** [comment]
> Again... Please Check if the device Work with the PC Software watchpower or Solarpower, when this will Work, the ESP Firmware will Work too. Actual only the communication from this sowares are supported.

where can I download Solarpower?

**Comment by Ching858** [comment]
> Again... Please Check if the device Work with the PC Software watchpower or Solarpower, when this will Work, the ESP Firmware will Work too. Actual only the communication from this sowares are supported.

I used wifi module via smartess it's works but when it comes to wemos it doesn't

**Comment by all-solutions** [comment]
> > Again... Please Check if the device Work with the PC Software watchpower or Solarpower, when this will Work, the ESP Firmware will Work too. Actual only the communication from this sowares are supported.
> 
> where can I download Solarpower?

https://www.mppsolar.com/v3/download/ under "monitoring software"

**Comment by all-solutions** [comment]
> > Again... Please Check if the device Work with the PC Software watchpower or Solarpower, when this will Work, the ESP Firmware will Work too. Actual only the communication from this sowares are supported.
> 
> I used wifi module via smartess it's works but when it comes to wemos it doesn't

If it work with smartess, then it use a complete other protocol (serial Modbus). Not compatible yet with solar2mqtt.

**Comment by Ching858** [comment]
![Messenger_creation_0c0cf1a1-7f23-43a5-b459-a44e3c33931e](https://github.com/user-attachments/assets/90388ef3-5fd1-4d99-a808-1ea19fcd6a65)

**Comment by Ching858** [comment]
![Messenger_creation_a208946a-563a-4847-b327-fe9a4e2494c0](https://github.com/user-attachments/assets/fb6ea46c-a980-41c4-aaf4-148c6bec3fcb)

**Comment by all-solutions** [comment]
What do you not understand about the statement that if it works with smartess, it does **NOT** work with solar2mqtt?
And that's exactly what your screenshot from the webserial says: **NAK**! The Wemos gets no response from the inverter. How can it, if the protocol does NOT fit on both sides?

**Comment by Ching858** [comment]
> What do you not understand about the statement that if it works with smartess, it does **NOT** work with solar2mqtt? And that's exactly what your screenshot from the webserial says: **NAK**! The Wemos gets no response from the inverter. How can it, if the protocol does NOT fit on both sides?

So what im going to do?

**Comment by softwarecrash** [comment]
> > What do you not understand about the statement that if it works with smartess, it does **NOT** work with solar2mqtt? And that's exactly what your screenshot from the webserial says: **NAK**! The Wemos gets no response from the inverter. How can it, if the protocol does NOT fit on both sides?
> 
> So what im going to do?

Nothing, my Software Doenst Work with your device
