### ISSUE TITLE
[Bug]: PV2 not monitored on  Daxtromn AGH-10.2KW (analog VICTOR NM-MAX-10.2KWs)

### ISSUE THREAD

**Issue by fastvd** [softwarecrash/Solar2MQTT-ESP8266#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

Greetings. thanks for the great program….
I have a VICTOR NM-MAX-10.2KWs inverter, it works based on the PI30 protocol. this inverter has 2 PV...the problem is that Solar2Mqtt reads only PV1...it also has a wifi dongle that shows data in the smartESS application, there is data from PV1 and PV2...so the question is how to read or OVERALL solar generation , or separately PV1 and PV2

### Screenshots / Fotos

![изображение_viber_2024-09-11_13-03-15-742](https://github.com/user-attachments/assets/97c8d37f-6a40-4c21-9eaa-025f5e880c67)
![изображение_viber_2024-09-11_13-03-15-780](https://github.com/user-attachments/assets/7ce1b7d8-929e-45a7-82c6-eca0b254b52e)
![image](https://github.com/user-attachments/assets/0437776d-f9ef-4c67-ac9e-b660c9802d63)

### Version

1.x.x and above

### Relevant livejson output

```json
{"EspData":{"Device_name":"Solar2MQTT","ESP_VCC":3.074,"Wifi_RSSI":-38,"sw_version":"1.1.7","Free_Heap":23704,"HEAP_Fragmentation":8,"json_memory_usage":942,"json_capacity":2048,"runtime":73,"ws_clients":0,"detect_protocol":2},"DeviceData":{"Device_Model":"VMII-NXPW5KW","Protocol_ID":"PI30"},"LiveData":{"AC_in_Voltage":244.2,"AC_in_Frequenz":49.9,"AC_out_Voltage":220.3,"AC_out_Frequenz":49.9,"AC_out_VA":4280,"AC_out_Watt":4265,"AC_out_percent":46,"Inverter_Bus_Voltage":465,"Battery_Voltage":55.4,"Battery_Charge_Current":27,"Battery_Percent":72,"Inverter_Bus_Temperature":42,"PV_Input_Current":8.2,"PV_Input_Voltage":414.7,"Battery_SCC_Volt":0,"Battery_Discharge_Current":0,"Status_Flag":10110,"Battery_voltage_offset_fans_on":0,"EEPROM_Version":0,"PV_Charging_Power":3336,"Device_Status":110,"Battery_Load":27,"PV_Input_Power":3312,"Inverter_Operation_Mode":"Battery","Time_until_absorb_charge":1,"Time_until_float_charge":0,"Tracker_temperature":0,"Inverter_temperature":32,"Battery_temperature":17,"Transformer_temperature":42,"Fan_speed":100,"Inverter_charge_state":"Float"}}
```

### What browsers are you seeing the problem on?

Chrome

**Comment by fastvd** [comment]
???

**Comment by softwarecrash** [comment]
hello,
without the communication protocol its not possible to implement more than one pv string

**Comment by fastvd** [comment]
> hello, without the communication protocol its not possible to implement more than one pv string

![366374997-a11ff0c4-6d74-49fe-b353-d42ec909f3ef](https://github.com/user-attachments/assets/f9118264-f040-4c20-95f4-f3202c414b07)

**Comment by fastvd** [comment]
!!! PI30 !!!
it was visible even on the 1st screen

**Comment by softwarecrash** [comment]
Stop using hordening Symbols, its Like angry...

So the PI30 Protocol is Not one single Protocol, it includes so i know more than 10 subversions, and much more variants, so for that what you need, i need a complete Protocol Snipet and Datasheet for it.

That all is Not easy as sound

**Comment by fastvd** [comment]
I'm sorry if you thought I was angry and wanted to offend someone) in fact, I just want to understand how my inverter works and read all the data I need.  now to the point...then how do I find out which protocol I have?  maybe there are some sniffers or just firmware that polls different protocols or take Wireshark and scan my existing wifi dongle?

**Comment by softwarecrash** [comment]
have the device a USB port? when yes, you can connect it with a PC, it will emulate a serial port, so you can use watchpower or solarpower software for monitoring and settings of the device, when this will work, you can enable the debug function of this software, this will write a bunch of log files, that what i need to see what the device talks.

for explaining, take a look at the documents here: 
https://github.com/softwarecrash/Solar2MQTT/tree/master/Protocol

there are more than one protocol of the PI30, and many different versions of command and answer strings, so we need to find out how to ask your device for the second PV string data.
in some protocols are a second string implemented, and in my firmware a function try to get this data, so its possible that your device need another request or send a different answer.

**Comment by fastvd** [comment]
> have the device a USB port? when yes, you can connect it with a PC, it will emulate a serial port, so you can use watchpower or solarpower software for monitoring and settings of the device, when this will work, you can enable the debug function of this software, this will write a bunch of log files, that what i need to see what the device talks.
> 
> for explaining, take a look at the documents here: https://github.com/softwarecrash/Solar2MQTT/tree/master/Protocol
> 
> there are more than one protocol of the PI30, and many different versions of command and answer strings, so we need to find out how to ask your device for the second PV string data. in some protocols are a second string implemented, and in my firmware a function try to get this data, so its possible that your device need another request or send a different answer.

![зображення_viber_2024-09-18_19-25-56-835](https://github.com/user-attachments/assets/f6321ac1-56a3-4f68-8a51-e26c3b81f47b)
yes, I have usb-rs232 and I can read and change data... but there is no info on the protocol... and I don't see where in the menu you can enable debugging...

**Comment by fastvd** [comment]
according to the link you gave, there are simply descriptions of various protocols, but there are no instructions on how to separate it... maybe I'm not looking there?

**Comment by softwarecrash** [comment]
The debug is Hidden, right click on the Icon in the taskbar and select enable debug

**Comment by all-solutions** [comment]
> yes, I have usb-rs232 and I can read and change data... but there is no info on the protocol... and I don't see where in the menu you can enable debugging...

You can enable it just in the tray icon (near the clock on your taskbar).
![image](https://github.com/user-attachments/assets/24b646ec-22a9-44dd-b27f-dfa95688b2b8)

**Comment by fastvd** [comment]
I found a program similar to watchpower.. this one http://www.multisibcontrol.net/ it looks like a lot more debug functions
![image](https://github.com/user-attachments/assets/812534b6-529b-4674-8fe1-68a6b937cb80)
![image](https://github.com/user-attachments/assets/f1440cd0-f99e-4162-aedf-126d9cf22a65)

**Comment by fastvd** [comment]
> > yes, I have usb-rs232 and I can read and change data... but there is no info on the protocol... and I don't see where in the menu you can enable debugging...
> 
> You can enable it just in the tray icon (near the clock on your taskbar). ![image](https://private-user-images.githubusercontent.com/17761850/368659929-24b646ec-22a9-44dd-b27f-dfa95688b2b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzgxNjYsIm5iZiI6MTcyNjY3Nzg2NiwicGF0aCI6Ii8xNzc2MTg1MC8zNjg2NTk5MjktMjRiNjQ2ZWMtMjJhOS00NGRkLWIyN2YtZGZhOTU2ODhiMmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE2NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2E5YjRlMmRmZTM2MWQ4YWQ3ZDJjZDUxNjYzMmI2Mjk0MmE3NDRlMWQ1MTYyNTE1M2U0MGMwYWU4NTg2YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JSSS58zY9YVv37Ox__8RrZh243NiMY9L_FrM6ixEj8Q)

![image](https://github.com/user-attachments/assets/aa6d1df2-254a-428d-90d2-171e767b1145)
I don't have debug mode ((((

**Comment by fastvd** [comment]
but with MultiSIBcontrol I can directly run different commands...
![image](https://github.com/user-attachments/assets/3e9858c2-180d-42c9-bb3a-b6b5fd3dc15b)

**Comment by all-solutions** [comment]
But QPIGS2 -> NAK means, this command is unkown by your Inverter... hm....

**Comment by fastvd** [comment]
this app also doesn't see PV2(((

I started QPIGS2 a few days ago directly from mqtt...but I didn't get a response then...the only thing I see is PV2 - smartESS via wifi dongle
![зображення_viber_2024-09-18_19-58-44-979](https://github.com/user-attachments/assets/998336ba-1a9a-47ed-aca4-580b3b160754)

**Comment by fastvd** [comment]
give links to watchpower where there is a debug mode

**Comment by all-solutions** [comment]
You are in the app in the console. What you enter there is sent directly to the inverter. If the QPIGS2 does not understand, then the data must come from somewhere else. 
And without having such a device here, this will be difficult or even impossible to find out.

**Comment by all-solutions** [comment]
> give links to watchpower where there is a debug mode

https://www.mppsolar.com/v3/download/  under Monitoring Software

**Comment by fastvd** [comment]
> > give links to watchpower where there is a debug mode
> 
> https://www.mppsolar.com/v3/download/ under Monitoring Software

![image](https://github.com/user-attachments/assets/a479848a-6ad0-4a7b-8639-0114fdf34fb0)

I downloaded a newer version, a floating window appeared, where the debug mode is checked immediately, the folder where the logs should be created opens immediately, but the logs themselves do not appear (((maybe it takes some time?

**Comment by all-solutions** [comment]
> maybe it takes some time?

yes

**Comment by fastvd** [comment]
25 minutes = 0 in debug(((

**Comment by softwarecrash** [comment]
Disconnect and reconnext the device

**Comment by fastvd** [comment]
![Screenshot_20240919_092518_Home Assistant](https://github.com/user-attachments/assets/83067acb-4e0b-4b91-9367-87f97307a617)

**Comment by fastvd** [comment]
https://github.com/odya/esphome-powmr-hybrid-inverter

**Comment by fastvd** [comment]
+ you need this




 - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "PV Voltage2"
    id: pv_voltage2
    address: 4563
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    lambda: |-
      return swapBytes(x);
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "PV Power2"
    id: pv_power2
    address: 4564
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 1
    lambda: |-
     return swapBytes(x);

**Comment by softwarecrash** [comment]
> * you need this
> 
> * platform: modbus_controller
>   modbus_controller_id: smg_inverter
>   name: "PV Voltage2"
>   id: pv_voltage2
>   address: 4563
>   register_type: holding
>   value_type: U_WORD
>   unit_of_measurement: "V"
>   device_class: voltage
>   state_class: measurement
>   accuracy_decimals: 1
>   lambda: |-
>   return swapBytes(x);
>   filters:
>   
>   * multiply: 0.1
> * platform: modbus_controller
>   modbus_controller_id: smg_inverter
>   name: "PV Power2"
>   id: pv_power2
>   address: 4564
>   register_type: holding
>   value_type: U_WORD
>   unit_of_measurement: "W"
>   device_class: power
>   state_class: measurement
>   accuracy_decimals: 1
>   lambda: |-
>   return swapBytes(x);

thats complete wrong....
this is modbus with registers!
my software read rs232 serial with qpigs commands, modbus not supprted atm

**Comment by fastvd** [comment]
I understand that you read the data in a different way...I just showed how I solved my problem and maybe you will take something useful for yourself to expand the functionality of your wonderful product!

**Comment by fastvd** [comment]
![image](https://github.com/user-attachments/assets/0d9c10d6-9fea-4dc1-b25a-38f1be586f3f)
this piece of code I pasted into the author's project to read PV2

**Comment by fastvd** [comment]
the data I see in HA matches what I see physically on the inverter display! this is what i needed!

**Comment by softwarecrash** [comment]
modbus register support are planed, but need a lot of time that i dont have yet

**Comment by fastvd** [comment]
anyway, thanks for your help and your time!

**Comment by VladimirButjko** [comment]
Tell me please, is it planned to fix the display of information on the second field of solar panels? On the inverter PowMr 10.2 exactly the same situation. Found a similar problem that was solved by changing the length of the request QPIGS2
https://github.com/manio/skymax-demo/issues/23
Maybe here it can be fixed in the same way.
