### ISSUE TITLE
easun smr II 5,5k log

### ISSUE THREAD

**Issue by ts1cos** [softwarecrash/Solar2MQTT-ESP8266#12]
please add easun smr II 5,5k
[log.zip](https://github.com/softwarecrash/Solar2MQTT/files/9309556/log.zip)

**Comment by softwarecrash** [comment]
Looks like the standart PI30 communication that works always with this adapter.

**Comment by softwarecrash** [comment]
[SMR II 5.5 232 Revo Protocol V03.zip](https://github.com/softwarecrash/Solar2MQTT/files/9314371/SMR.II.5.5.232.Revo.Protocol.V03.zip)

**Comment by softwarecrash** [comment]
@ts1cos i have made a little change, when you able to self compile, you can try it
