### ISSUE TITLE
[HELP] I am not receiving data PowMr 6.2 kW

### ISSUE THREAD

**Issue by IvanSerevko** [softwarecrash/Solar2MQTT-ESP8266#124]
### Please enter the name of the device manufacturer
PowMr

### Please enter the device type
6.2 kW

### Used Hardware
Wemos D1 Mini
rs232 to ttl
dc-dc 12 to 5v

Hello, I did everything according to the instructions, but I have a problem with receiving data after connecting via mqtt, when I configure the connection to mqtt, the data is not displayed, and also in mqtt explorer I see my inverter but do not see its data, what could be the problem, please help me

**Comment by vytya** [comment]
I don't see any data either on PowMr 6.2.
BTW I tried couple esp32 solutions and also without success. 

But powmr wifi module is working well.

**Comment by IvanSerevko** [comment]
same situation

**Comment by softwarecrash** [comment]
hey
have one of our devices a serial port or usb port that allow communication with a pc? so that we can try to get the communication between the pc software and the device?

**Comment by IvanSerevko** [comment]
rs232 for wifi  and rs485 for bms

**Comment by softwarecrash** [comment]
you can try to use a rs232 cable or a adapter rs232-usb and connect it with a pc, and use watchpower or solarpower, hope you get data from the device

**Comment by vytya** [comment]
![image](https://github.com/user-attachments/assets/10ec9cfd-ac66-4a9f-a592-79191bacd1df)
Yee! It started to working. 
As it turned out I connected to wrong rs232 pins.

@IvanSerevko можеш написати якщо що в тг @vytya

**Comment by softwarecrash** [comment]
can it close?

**Comment by IvanSerevko** [comment]
Yes, I will try other components to solve this problem
