### ISSUE TITLE
[HELP] I am not receiving data Voltronic Axpert MKS IV 5.6 Kw

### ISSUE THREAD

**Issue by Pinky-bit** [softwarecrash/Solar2MQTT-ESP8266#126]
### A clear and concise description of what the problem is.

Please enter the name of the device manufacturer
SolarPower 24 Axpert MKS IV 5.6 Kw

Used Hardware
Wemos D1 Mini
DB9 rs232 to ttl

Hi, I followed all the instructions but I can't see any inverter data, no Livedata. The wemos D1 mini transmits. Do I need to change some parameters? Thank you

**Comment by softwarecrash** [comment]
can you show me your setup and wireing with photos?

**Comment by Pinky-bit** [comment]
> can you show me your setup and wireing with photos?

I solved it by improving the wiring connections. Thank you
