### ISSUE TITLE
IGridSV-IV5.6KW

### ISSUE THREAD

**Issue by Cryptimo** [softwarecrash/Solar2MQTT-ESP8266#13]
Hier ein Logfile vom IGridSV-IV5.6KW (Erzeugt mit Rechtsklick auf das Tray-Icon des Programms Solarpower). Bei 10:06 Uhr habe ich die Einstellung für die LED Anzeige geändert (Ist zwar unwichtig, aber um überhaupt mal eine Einstellung zu ändern). Im beigefügten LOG nach dem Stichwort "LED" suchen.

Es gibt nur noch eine Log-Datei. Früher muss es bei ähnlichen Modellen mehrere Dateien gegeben haben. Hier entsteht aber nur eine Datei.
[2022-08-30 IGridSV-IV5.6KW.log](https://github.com/softwarecrash/Solar2MQTT/files/9451213/2022-08-30.IGridSV-IV5.6KW.log)

![160db8dc773a4f6cb24cc48592d80b84_1800x](https://user-images.githubusercontent.com/76493996/187390923-34f108ca-b5c0-4a08-981f-88a5b4da0983.jpg)
![IGridSV-IV5 6KW - Solarpower 1](https://user-images.githubusercontent.com/76493996/187397657-da1e1eaa-2a87-4b73-99ec-447b0ba92dbd.jpg)
![IGridSV-IV5 6KW - Solarpower 2](https://user-images.githubusercontent.com/76493996/187397671-94020738-1530-4e4d-a30e-a7bda7adfcb3.jpg)

**Comment by Cryptimo** [comment]
Hier die Anleitung:

[IGridSV-IV5.6KW - Manual Ver.1.0.pdf](https://github.com/softwarecrash/Solar2MQTT/files/9451574/IGridSV-IV5.6KW.-.Manual.Ver.1.0.pdf)

**Comment by softwarecrash** [comment]
komma separierte werte, kein PI30 protokol, wird später hinzugefügt.
welche baudrate nutzt solarpower?

**Comment by mihaigsm2003** [comment]
this is P18 protocol

**Comment by rolsch** [comment]
Hi, i have an IGridSV-IV5.6KW.
How can i support this project?
Actual, i'll build the ESP-Adapter for this :-)

Ist diese Aussage noch aktuell bei den fertigen Modulen im Shop?

Die aktuell bei Github releaste Firmware funktioniert nicht mit dieser Platine!
Auch nicht der P18-Fork, dieser wird nicht von uns gepflegt und betreut.

**Comment by softwarecrash** [comment]
> Hi, i have an IGridSV-IV5.6KW. How can i support this project? Actual, i'll build the ESP-Adapter for this :-)
> 
> Ist diese Aussage noch aktuell bei den fertigen Modulen im Shop?
> 
> Die aktuell bei Github releaste Firmware funktioniert nicht mit dieser Platine! Auch nicht der P18-Fork, dieser wird nicht von uns gepflegt und betreut.

welche aussage im shop?
mit der platine funktioniert aktuell nur eine angepasste firmware, die releases gehen noch nicht.

der p18 fork geht genausowenig da dort auch eine anpassung fehlt.

funktioniert der inverter mit watchpower?

**Comment by mihaigsm2003** [comment]
> Hi, i have an IGridSV-IV5.6KW. How can i support this project? Actual, i'll build the ESP-Adapter for this :-)
> 
> Ist diese Aussage noch aktuell bei den fertigen Modulen im Shop?
> 
> Die aktuell bei Github releaste Firmware funktioniert nicht mit dieser Platine! Auch nicht der P18-Fork, dieser wird nicht von uns gepflegt und betreut.

use this link for your inverter, need compile, but firs add your data in settings file. For moment i remove custom fields, but you can modify if need:

https://github.com/mihaigsm2003/Read-Data-Inverter-P18

**Comment by softwarecrash** [comment]
> > Hi, i have an IGridSV-IV5.6KW. How can i support this project? Actual, i'll build the ESP-Adapter for this :-)
> > Ist diese Aussage noch aktuell bei den fertigen Modulen im Shop?
> > Die aktuell bei Github releaste Firmware funktioniert nicht mit dieser Platine! Auch nicht der P18-Fork, dieser wird nicht von uns gepflegt und betreut.
> 
> use this link for your inverter, need compile, but firs add your data in settings file. For moment i remove custom fields, but you can modify if need:
> 
> https://github.com/mihaigsm2003/Read-Data-Inverter-P18

this will not work with the PCB edition!

actual i rewrite the whole code for a new edition with more support for devices.... need time

**Comment by rolsch** [comment]
Hi Rocky.

 

Thanks for the info. I hope that in the near future the PCB edition works with the public github release AND with the P18 code.

 

Von: Rocky ***@***.***> 
Gesendet: Samstag, 29. Juli 2023 13:12
An: softwarecrash/Solar2MQTT ***@***.***>
Cc: rolsch ***@***.***>; Comment ***@***.***>
Betreff: Re: [softwarecrash/Solar2MQTT] IGridSV-IV5.6KW (Issue #13)

 

Hi, i have an IGridSV-IV5.6KW. How can i support this project? Actual, i'll build the ESP-Adapter for this :-)
Ist diese Aussage noch aktuell bei den fertigen Modulen im Shop?
Die aktuell bei Github releaste Firmware funktioniert nicht mit dieser Platine! Auch nicht der P18-Fork, dieser wird nicht von uns gepflegt und betreut.

use this link for your inverter, need compile, but firs add your data in settings file. For moment i remove custom fields, but you can modify if need:

https://github.com/mihaigsm2003/Read-Data-Inverter-P18

this will not work with the PCB edition!

**Comment by mihaigsm2003** [comment]
> > > Hi, i have an IGridSV-IV5.6KW. How can i support this project? Actual, i'll build the ESP-Adapter for this :-)
> > > Ist diese Aussage noch aktuell bei den fertigen Modulen im Shop?
> > > Die aktuell bei Github releaste Firmware funktioniert nicht mit dieser Platine! Auch nicht der P18-Fork, dieser wird nicht von uns gepflegt und betreut.
> > 
> > 
> > use this link for your inverter, need compile, but firs add your data in settings file. For moment i remove custom fields, but you can modify if need:
> > https://github.com/mihaigsm2003/Read-Data-Inverter-P18
> 
> this will not work with the PCB edition!
> 
> actual i rewrite the whole code for a new edition with more support for devices.... need time

why not work? i think both use same hardware. yes, my software is optimized for original interface from china , work with panel leds.

**Comment by softwarecrash** [comment]
> > > > Hi, i have an IGridSV-IV5.6KW. How can i support this project? Actual, i'll build the ESP-Adapter for this :-)
> > > > Ist diese Aussage noch aktuell bei den fertigen Modulen im Shop?
> > > > Die aktuell bei Github releaste Firmware funktioniert nicht mit dieser Platine! Auch nicht der P18-Fork, dieser wird nicht von uns gepflegt und betreut.
> > > 
> > > 
> > > use this link for your inverter, need compile, but firs add your data in settings file. For moment i remove custom fields, but you can modify if need:
> > > https://github.com/mihaigsm2003/Read-Data-Inverter-P18
> > 
> > 
> > this will not work with the PCB edition!
> > actual i rewrite the whole code for a new edition with more support for devices.... need time
> 
> why not work? i think both use same hardware. yes, my software is optimized for original interface from china , work with panel leds.

ah, missunderstanding.
your software, and the actual release here, will not work with the PCB that we sell. the PCB need a modified variant.
i work on it, so the code have heavy modifications. when it will work was i try, i can adapt the p18, and sometimes the other protocols too.
but first i must solve a issue on a other project.

**Comment by softwarecrash** [comment]
support added  with  V1.1.0
