### ISSUE TITLE
[Bug]: Command MCHGC not working

### ISSUE THREAD

**Issue by ghsrg** [softwarecrash/Solar2MQTT-ESP8266#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Other (please write your hardware in 'What happened?')

### What happened?

Command MCHGC not working. 
QMCHGCR  return 010 020 030 040 050 060 070 080
But MCHGC010, MCHGC020, MCHGC030 etc return NAK

With PDx, PEx, PCP02, PCP01 no problem
I'm using Powmr 4.2 and NodeMCU analog WeMos D1 mini  Flash 4Mb

### Screenshots / Fotos

![image](https://github.com/user-attachments/assets/e7bf6833-31ed-4fb8-a122-ee2568843e6e)

### Steps To Reproduce

Sending [MCHGC010] to Device
[C: MCHGC010][CR: 7373][CC: 7373][L:   3]

### Version

1.x.x and above

### Relevant livejson output

```json
{"EspData":{"Device_name":"Solar2MQTT","ESP_VCC":2.984,"Wifi_RSSI":-33,"sw_version":"1.1.7","Free_Heap":18848,"HEAP_Fragmentation":25,"json_memory_usage":939,"json_capacity":2048,"runtime":204,"ws_clients":1,"detect_protocol":2},"DeviceData":{"Device_Model":"VMII-NXPW5KW","Protocol_ID":"PI30"},"LiveData":{"AC_in_Voltage":225.1,"AC_in_Frequenz":49.9,"AC_out_Voltage":225.1,"AC_out_Frequenz":49.9,"AC_out_VA":607,"AC_out_Watt":496,"AC_out_percent":14,"Inverter_Bus_Voltage":440,"Battery_Voltage":27.7,"Battery_Charge_Current":4,"Battery_Percent":100,"Inverter_Bus_Temperature":40,"PV_Input_Current":0,"PV_Input_Voltage":0,"Battery_SCC_Volt":0,"Battery_Discharge_Current":0,"Status_Flag":10101,"Battery_voltage_offset_fans_on":0,"EEPROM_Version":0,"PV_Charging_Power":0,"Device_Status":110,"Battery_Load":4,"PV_Input_Power":0,"Inverter_Operation_Mode":"Line","Time_until_absorb_charge":0,"Time_until_float_charge":0,"Tracker_temperature":0,"Inverter_temperature":40,"Battery_temperature":28,"Transformer_temperature":31,"Fan_speed":35,"Inverter_charge_state":"Float"}}
```

### What browsers are you seeing the problem on?

Chrome

**Comment by softwarecrash** [comment]
https://github.com/softwarecrash/Solar2MQTT/blob/master/Protocol/PI30MAX.Communication.Protocol20210217.pdf
try like this
![image](https://github.com/user-attachments/assets/64ba68fd-7ade-418c-9bb1-b88266d42feb)
