### ISSUE TITLE
[HELP] How to update Wifi settings?

### ISSUE THREAD

**Issue by EOUpSL93Y** [softwarecrash/Solar2MQTT-ESP8266#135]
### A clear and concise description of what the problem is.

Hello. Is there any way to update wifi connection settings?

**Comment by all-solutions** [comment]
Press the reset button on the Wemos 10 times in quick succession. It will then delete the entire configuration and you can set everything up again.

**Comment by softwarecrash** [comment]
or bring the esp out of range of the old wifi, after a short time it will open the AP mode

**Comment by EOUpSL93Y** [comment]
1. It's a ESP01;
2. I have access to web interface, so i can press "Reset ESP". But i don't want to reconfigure everything again, i just want to change AP ESSID to another (with stronger signal).

**Comment by all-solutions** [comment]
Then switch off the other one for the time being. Currently it is not possible to change it if the configured Wifi is still present.

**Comment by EOUpSL93Y** [comment]
It would be nice to have such setting.

**Comment by all-solutions** [comment]
As I said, not possible at the moment. And let's be honest: what “everything” needs to be reconfigured?
- MQTT
- Topic
- Possibly refresh time

BTW: Two different Wifi's in the house? Why via different SSIDs?

**Comment by EOUpSL93Y** [comment]
> As I said, not possible at the moment.

Ok.

> BTW: Two different Wifi's in the house?

1 in the house as a main AP, 2nd for other locations (close to house) first of all for "smart" modules.
So, for example, in ESP Home i have 2 wifi definitions in device config, i can configure/debug it at home and then install in any other location.
