### ISSUE TITLE
Isolar SMH 3KW

### ISSUE THREAD

**Issue by ddragon11** [softwarecrash/Solar2MQTT-ESP8266#14]
Hi, in reference to yesterday discussion on discord I attach a file .
[debug.zip](https://github.com/softwarecrash/Solar2MQTT/files/9567649/debug.zip)

**Comment by softwarecrash** [comment]
try this
[firmware.zip](https://github.com/softwarecrash/Solar2MQTT/files/9594149/firmware.zip)

**Comment by ddragon11** [comment]
Not working

**Comment by ddragon11** [comment]
Protocol Comunication RS232
[PS MPS 232通讯协议.pDf](https://github.com/softwarecrash/Solar2MQTT/files/9598381/PS.MPS.232.pDf)

**Comment by softwarecrash** [comment]
close, its working
