### ISSUE TITLE
New working device EASun Isolar SPH 3k

### ISSUE THREAD

**Issue by MaGumagus** [softwarecrash/Solar2MQTT-ESP8266#147]
### Please enter the name of the device manufacturer

EASun

### Please enter the device type

Isolar SPH 3k

**Comment by MaGumagus** [comment]
the only issue is 

Temperature .... 448°C   :)

**Comment by softwarecrash** [comment]
thank you,
the temperature is not a issue, the device delivers this value in the wrong format
