### ISSUE TITLE
[FEATURE] rename data PV to PV1 from mppt1 controller; use correct name input - not charging, charging its for battery

### ISSUE THREAD

**Issue by vpm** [softwarecrash/Solar2MQTT-ESP8266#165]
### Is your feature request related to a problem? Please describe

1) I have 2 mppt controllers, many sensors have data for all pv, but look like data from mppt1 and others data 
2) i think PV2_Charging_Power its not corect name for Input_power, beacause charging its for battery charging
![Снимок экрана в 2024-10-21 17-30-11](https://github.com/user-attachments/assets/a27645dc-8318-4966-b88a-1791ba5ed993)

### Describe the solution you'd like

rename PV to PV1 from mppt1 controller
rename Charging_power to Input_power

### Describe alternatives you've considered

.

**Comment by softwarecrash** [comment]
thats what stay in the protocol, and pv charging power is correct too
