### ISSUE TITLE
MUST PV18 support

### ISSUE THREAD

**Issue by taHC81** [softwarecrash/Solar2MQTT-ESP8266#18]
Hello, could you please consider adding new device MUST PV18 series, registers are described in https://github.com/andremiller/must-inverter-python-monitor . If you navigate me, I can work on that - not sure if your project could easily handle new protocol. Thanks.

**Comment by softwarecrash** [comment]
hello,
that looks not similar with my code. so the baud rate is not the same and the protocol is verry different.

so in future i will rewrite the thing that everyone self can make a file with the communication style and command, but that need time. at the moment i work on the daly project

**Comment by taHC81** [comment]
Sure, take your time ;) I'm currently using the tiny desktop PC (Lenovo M73) running the script and publishing it via MQTT and also storing to the DB for Grafana visualization.

**Comment by softwarecrash** [comment]
not supportable, its modbus not serial
