### ISSUE TITLE
[HELP] <title> Does not read data from the inverter axioma energy ismppt bf 3000

### ISSUE THREAD

**Issue by Dior34** [softwarecrash/Solar2MQTT-ESP8266#185]
### A clear and concise description of what the problem is.

Does not read data from the inverter axioma energy ismppt bf 3000.
Several times it was possible to get data in the Home Assistant, this confirms that the settings are correct. In this case, the Solar2MQTT_d1_mini_1.2.0-Pre4.bin firmware was used. The data was obtained 3 times for 2-3 hours. The rest of the time, either does not read anything at all or 0
Firmware changes do not help.
at the same time, wachpower receives data only if the version is older than version 1.1.9. i.e. 1.1.10 does not receive 
Connecting with one wire to the TTL board and to the computer

### Additional context

![HA](https://github.com/user-attachments/assets/7d00b8f5-40cc-4da4-a0a8-0194959d69bc)
![camphoto_959030623](https://github.com/user-attachments/assets/b78dbd26-7fb6-4dbf-9ec2-642974d787fe)
![SharedScreenshot](https://github.com/user-attachments/assets/59e31fee-ed86-40a0-9b3d-4a48f7fe45e8)
![wachpower ](https://github.com/user-attachments/assets/d82ca8bc-fc77-46db-87a1-c931aa03ded3)
![Знімок екрана 2024-12-02 182404](https://github.com/user-attachments/assets/1c66df9e-5631-4ef0-905a-0700f85c0d7c)

**Comment by Dior34** [comment]
![Знімок екрана 2024-12-01 212914](https://github.com/user-attachments/assets/83d4d049-9553-4a38-89f3-983d8024a147)

**Comment by softwarecrash** [comment]
What tells the webserial (or USB serial) from the ESP when No Data is recived?

**Comment by Dior34** [comment]
﻿Надіслано з iPhone2 груд. 2024 р. о 00:04 Rocky ***@***.***> пише:﻿
What tells the webserial (or USB serial) from the ESP when No Data is recived?

**Comment by Dior34** [comment]
I used different boards based on 8266mod. also differences in TTL boards from different manufacturers
![photo_2024-12-02_09-59-19](https://github.com/user-attachments/assets/cdb145a8-2a67-499e-8921-fa4b509cd849)
![photo_2024-12-02_09-59-17](https://github.com/user-attachments/assets/c6bf8a61-61d0-43f1-94ec-74e54199540d)
![photo_2024-12-02_09-59-15](https://github.com/user-attachments/assets/286a422a-eddc-4c47-b01c-b43b60dabab7)
![photo_2024-12-02_09-59-13](https://github.com/user-attachments/assets/0d89413d-d69a-4890-8aba-dea4ea2a1ef8)
![photo_2024-12-02_09-59-05](https://github.com/user-attachments/assets/5eeee90f-bd71-4dfb-b736-17990a93a581)
![photo_2024-12-02_10-03-17](https://github.com/user-attachments/assets/646e5e41-fe74-401c-ada4-483290bcb21c)
![photo_2024-12-02_10-23-00](https://github.com/user-attachments/assets/1da6489d-f036-46e9-b3e4-26b9eec0e126)



There is a photo of a successful connection left
![photo_2024-12-02_10-04-52](https://github.com/user-attachments/assets/a9adda44-9808-4fcc-9cd8-c47bc925a75a)

If the connection is successful, the PI30 inverter protocol is determined
There are still photos of various unsuccessful connections . 

connected with connectors, then switched to soldering. (Immediately after soldering there was the first success)
tried under different names

Web Console   v 2.2.0 pre.6
  
[WebSerial] Connecting...
[WebSerial] Connected...
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
----------------- End Autodetect -----------------
ProzessData P:0 C:0
WS data send
MQTT Client State: 0
Data sent to MQTT
[C:    QPI][CR:    0][CC:    0][L:   3]
QPI:		NOA (Length: 3)
[C: ^P005PI][CR:    0][CC:    0][L:   3]
^P005PI:		NOA (Length: 3)
Try Autodetect Protocol
[C:    QPI][CR:    0][CC:    0][L:   3]
QPI:		NOA (Length: 3)
[C: ^P005PI][CR:    0][CC:    0][L:   3]
^P005PI:		NOA (Length: 3)
Try Autodetect Protocol
[C:    QPI][CR:    0][CC:    0][L:   3]
QPI:		NOA (Length: 3)
[C: ^P005PI][CR:    0][CC:    0][L:   3]
^P005PI:		NOA (Length: 3)
Try Autodetect Modbus device
Init MUST PV/PH 18 protocol, baud 19200, modbusAddr 4
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Init DEYE protocol, baud 9600, modbusAddr 1
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Init Anenji protocol, baud 9600, modbusAddr 1
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
Response Timed Out
Response Timed Out
Time-out
Request failed!
----------------- End Autodetect ----------------



-
-
-
-
-

-



Web Console       v  1.2.0   pre.4
  


[18:08:24] ----------------- End Autodetect -----------------



[18:08:24] MQTT Client State: 0

[18:08:24] ----------------- Start Autodetect -----------------

[18:08:26] [C:   QPI][CR:    0][CC:    0][L:   3]

[18:08:26] 

[18:08:26] QPI:		NAK (Length: 3)

[18:08:26] 

[18:08:28] [C: ^P005PI][CR:    0][CC:    0][L:   3]

[18:08:28] 

[18:08:28] ^P005PI:		NAK (Length: 3)

[18:08:28] 

[18:08:28] Try Autodetect Protocol

[18:08:28] 

[18:08:30] [C:   QPI][CR:    0][CC:    0][L:   3]

[18:08:30] 

[18:08:30] QPI:		NAK (Length: 3)

[18:08:30] 

[18:08:32] [C: ^P005PI][CR:    0][CC:    0][L:   3]

[18:08:32] 

[18:08:32] ^P005PI:		NAK (Length: 3)

[18:08:32] 

[18:08:32] Try Autodetect Protocol

[18:08:32] 

[18:08:34] [C:   QPI][CR:    0][CC:    0][L:   3]

[18:08:34] 

[18:08:34] QPI:		NAK (Length: 3)

[18:08:34] 

[18:08:36] [C: ^P005PI][CR:    0][CC:    0][L:   3]

[18:08:36] 

[18:08:36] ^P005PI:		NAK (Length: 3)

[18:08:36] 

[18:08:37] Try Autodetect Modbus device

[18:08:37] 

[18:08:38] Response Timed Out

[18:08:38] 

[18:08:40] Response Timed Out

[18:08:40] 

[18:08:40] Time-out

[18:08:40] 

[18:08:40] Request failed!

[18:08:41] 

[18:08:42] Response Timed Out

[18:08:42] 

[18:08:44] Response Timed Out

[18:08:44] 

[18:08:44] Time-out

[18:08:44] 

[18:08:45] Request failed!

[18:08:45] 

[18:08:46] Response Timed Out

[18:08:46] 

[18:08:48] Response Timed Out

[18:08:48] 

[18:08:48] Time-out

[18:08:49] 

[18:08:49] Request failed!

[18:08:49] 

[18:08:50] Response Timed Out

[18:08:51] 

[18:08:52] Response Timed Out

[18:08:52] 

[18:08:53] Time-out

[18:08:53] 

[18:08:53] Request failed!

[18:08:53] 

[18:08:53] ----------------- End Autodetect -----------------

POWER SUPPLY of boards from USB from a separate power supply unit or computer

**Comment by softwarecrash** [comment]
I have No Idea why it Work and dont Work later.
Looks Like a communication issue

**Comment by Dior34** [comment]
Please tell me if it is possible to manually poll an unconnected inverter to check if it responds to requests.4 груд. 2024 р. о 00:46 Rocky ***@***.***> пише:﻿
I have No Idea why it Work and dont Work later.
Looks Like a communication issue

**Comment by softwarecrash** [comment]
you can try to force a protocol by paste following in the webserial console

setp x
  1=  PI18,
   2= PI30,
   3= MODBUS_MUST,
   4= MODBUS_DEYE,
   5= MODBUS_ANENJI,
   6= PROTOCOL_TYPE_MAX

**Comment by Dior34** [comment]
Still managed to start.
Ordered a new (third) TTL board. And everything worked.
Can you add this model of hybrid inverter as working

Thanks!
