### ISSUE TITLE
[Bug]: PowMR POW-HVM6.2M-48V

### ISSUE THREAD

**Issue by nickcheban** [softwarecrash/Solar2MQTT-ESP8266#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

Inverter doesn't send data
Inverter firmware: U1 21 12

### Screenshots / Fotos

![image](https://github.com/user-attachments/assets/15b8e4df-1d92-4836-878f-e9947f9144b3)
![image](https://github.com/user-attachments/assets/da236fb0-9940-43c2-934f-a2d397a7ea21)
![image](https://github.com/user-attachments/assets/61dd766f-b687-4569-91c8-23372ae89bca)

### Version

1.x.x and above

### Relevant livejson output

```json
{"EspData":{"Device_name":"Solar2MQTT","ESP_VCC":2.994,"Wifi_RSSI":-52,"sw_version":"1.1.8","Free_Heap":20176,"HEAP_Fragmentation":12,"json_memory_usage":372,"json_capacity":2048,"runtime":401,"ws_clients":1,"detect_protocol":0},"DeviceData":{},"LiveData":{}}
```

### What browsers are you seeing the problem on?

no Issue with the Browser or WebUI

**Comment by nickcheban** [comment]
version 0.5.1
Relevant livejson output
{"gridV":0,"gridHz":0,"acOutV":0,"acOutHz":0,"acOutVa":0,"acOutW":0,"acOutPercent":0,"busV":0,"heatSinkDegC":0,"battV":0,"battPercent":0,"battChargeA":0,"battDischargeA":0,"sccBattV":0,"solarV":0,"solarA":0,"solarW":0,"cSOC":0,"iv_mode":"","device_name":"pm"}
![Screenshot 2024-12-20 061757](https://github.com/user-attachments/assets/efa6aba9-1086-4f8b-8489-4f54aadc1f9b)

**Comment by softwarecrash** [comment]
hello,
have you double checked your wireing?
can you show us your swtup and wireing?

**Comment by nickcheban** [comment]
it was my fault
i soldered one of the wires badly

**Comment by nickcheban** [comment]
close the issue please
