### ISSUE TITLE
Blynk 2.0 integration

### ISSUE THREAD

**Issue by haadi76** [softwarecrash/Solar2MQTT-ESP8266#25]
Ok, so not to mention but in my case mqtt sucks and I am bound to check the stats through a browser typing the ip address of the esp8266 which frequently changes. Also, I don't mean to calculate the units produced myself and want it to be done by the esp8266 itself

Therefore, i would like to request integration of blynk 2.0 so that i can get that beautiful graphs and most importantly don't have to pay for cloud mqtt services in order to monitor by solar system production when I am away. I don't hate setting up hundreds of data stream and organizing the dashboard of my blynk app if have to do it only **once**. Whereas with current setup I can't set up dhcp binding on my router as it disturbs the other functionality of the router (this might occur only on my end but still, isn't the aim to give an alternative to those pricey wifi modules for inverter)

Lastly, I would like to add that please make the code a little bit easier to understand and edit. truly i would say that the system worked in one go but any chances of further improvement in the software side was clearly impossible from my side. Thus, even if the code is not made easier just add blynk support.

**Comment by softwarecrash** [comment]
sorry but actual i dont will add blynk support.
