### ISSUE TITLE
Kodak/Axpert/PIP OG5.48

### ISSUE THREAD

**Issue by dazzlersa** [softwarecrash/Solar2MQTT-ESP8266#26]
Your repo looks perfect for what I am doing to link to Home Assistant, amazing work!!

What are the chances that the D1-Mini is powered and communicates on the built-in USB port D1 Mini side and then the USB output (Micro-USB) on the Inverter?

The Micro USB port works as I have had ned-Kellys' Voltronic working perfectly on it on a Pi. But it popped, unfortunately.

I am hoping the pics help to explain. Basically USB to USB.

![WhatsApp Image 2023-02-17 at 20 17 28 (1)](https://user-images.githubusercontent.com/892876/219751704-c2baf829-9c3e-4c34-8702-94f7f9748692.jpeg)

![WhatsApp Image 2023-02-17 at 20 17 28](https://user-images.githubusercontent.com/892876/219752588-372f92b8-c3ff-4aaa-9a94-a3f41c3be88f.jpeg)

TIA 

Daz

**Comment by dazzlersa** [comment]
After reading every thread in the issues I tried the big max3232 and also tried the Rx- Tx and Rx-RX combos, still get nothing on the webpage. Any ideas?
![WhatsApp Image 2023-02-18 at 06 57 34](https://user-images.githubusercontent.com/892876/219844425-fb5e4865-d643-4e2d-b6d7-79a7dd814fef.jpeg)
![WhatsApp Image 2023-02-18 at 08 10 33 (1)](https://user-images.githubusercontent.com/892876/219844427-1d342810-8a9e-419b-b805-ac8dacb5210b.jpeg)
![WhatsApp Image 2023-02-18 at 08 10 33](https://user-images.githubusercontent.com/892876/219844428-8f11bfdd-170d-4395-88d9-334032c9515b.jpeg)
![WhatsApp Image 2023-02-18 at 08 10 32 (1)](https://user-images.githubusercontent.com/892876/219844429-233708bd-0aaf-4e21-a0c2-1cce430a3e3e.jpeg)
![WhatsApp Image 2023-02-18 at 08 10 32](https://user-images.githubusercontent.com/892876/219844430-e6e65c76-e194-4e58-bd2a-2334e47dcdb2.jpeg)
![WhatsApp Image 2023-02-18 at 06 57 35 (2)](https://user-images.githubusercontent.com/892876/219844431-d94e15f1-0ab4-4714-ba86-8c9e1f0fa13d.jpeg)
![WhatsApp Image 2023-02-18 at 06 57 35 (1)](https://user-images.githubusercontent.com/892876/219844433-2b6eec05-7bcd-4914-8b3f-43c1919aad96.jpeg)
![WhatsApp Image 2023-02-18 at 06 57 35](https://user-images.githubusercontent.com/892876/219844434-8b580c84-eb34-4ed6-84df-784a50f1e02e.jpeg)

**Comment by dazzlersa** [comment]
Sorry they aren't in order.

**Comment by softwarecrash** [comment]
sorry the late answer.
a connection usb-usb is not possibil, that idea need a usb host shielt and this is verry complex and expensive.
when xou not get data fromn the inverter please connect it over serial to the pc and start watchpower, then activate debug in watchpower, that will create a bunch of files. this files i need to check it will work

**Comment by softwarecrash** [comment]
@dazzlersa work this inverter with serial in korrekt order?

**Comment by softwarecrash** [comment]
no issue
