### ISSUE TITLE
Masterpower Omega-UM3KVA

### ISSUE THREAD

**Issue by ghost** [softwarecrash/Solar2MQTT-ESP8266#27]
Die Daten des Masterpower Omega UM3KVA werden in der Solar2MQTT V0.5.1 nicht korrekt angezeigt. Die Temperatur kommt vom Masterpower schon in den Rohdaten falsch. 

**Screenshots**

![Screenshot 2023-04-10 104725](https://user-images.githubusercontent.com/58141879/230870976-d077bfbe-8287-4bf4-863a-6ba4943cae5c.png)
![Screenshot 2023-04-10 104646](https://user-images.githubusercontent.com/58141879/230870983-790b4f5f-2f95-40ac-8e05-ce8850923f0b.png)
[debug.zip](https://github.com/softwarecrash/Solar2MQTT/files/11189323/debug.zip)

**Comment by ghost** [comment]
Zwischen den beiden Screenshots liegen ein paar minuten Zeit, daher die unterschiede.

**Comment by softwarecrash** [comment]
kannst du deinen verkäufer kontaktieren das er dir das pdf für das rs232 protokol schickt?

**Comment by ghost** [comment]
Hi, mache ich. Hoffe sie schicken was.Lgm --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.04.23, 19:23 schrieb Rocky ***@***.***>:

   
  kannst du deinen verkäufer kontaktieren das er dir das pdf für das rs232 protokol schickt?

**Comment by softwarecrash** [comment]
> 
>  
>   
>   
>  
>  Hi, mache ich. Hoffe sie schicken was.Lgm --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.04.23, 19:23 schrieb Rocky ***@***.***>:
> 
>    
>   kannst du deinen verkäufer kontaktieren das er dir das pdf für das rs232 protokol schickt? 
>   —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Super, danke.
Ich kann den Wert der als Temperatur angezeigt wird absulut nicht zuordnen.
Man könnte es jetzt so hinfriemeln das es passt, aber mit Protokoll wäre das deutlich einfachet

**Comment by all-solutions** [comment]
Hallo Michael,
ich habe den gleichen Hybriden. Spannend, bei mir wird die Temperatur problemlos angezeigt. Dafür kein SCC. Den gibt meiner aber tatsächlich nicht raus.
Den einzigen Unterschied, den ich zwischen Deinem und meinem sehe, sind die CPU-Software-Versionen. Ich habe als Haupt die 47.00 und als Zweit die 103.24.
Oder ist evtl. in Deinem der Temp-Sensor "Schrott"? Du schreibst ja, dass schon die Rohdaten vom Masterpower falsch sind.

**Comment by softwarecrash** [comment]
nur so am rande, welche temperatur wäre den realisitsch? war der unter last das es 68,9 sein könnten?
oder hast du die möglichkeit die einheiten am display einzustellen? ggf steht es auf Fahrenheit

**Comment by ghost** [comment]
Hallo zusammen,
Mir scheint unter den aktuellen Bedingungen ein Milli -Fahrenheit Wert realistisch. Wobei das einem Blick in die Glaskugel gleich kommt. Die Einheiten kann ich leider nirgendwo einstellen

**Comment by ghost** [comment]
> Hallo Michael, ich habe den gleichen Hybriden. Spannend, bei mir wird die Temperatur problemlos angezeigt. Dafür kein SCC. Den gibt meiner aber tatsächlich nicht raus. Den einzigen Unterschied, den ich zwischen Deinem und meinem sehe, sind die CPU-Software-Versionen. Ich habe als Haupt die 47.00 und als Zweit die 103.24. Oder ist evtl. in Deinem der Temp-Sensor "Schrott"? Du schreibst ja, dass schon die Rohdaten vom Masterpower falsch sind.

Das der Sensor Schrott ist könnte auch sein.

**Comment by ghost** [comment]
> Hi, mache ich. Hoffe sie schicken was.Lgm --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.04.23, 19:23 schrieb Rocky ***@***.***>: kannst du deinen verkäufer kontaktieren das er dir das pdf für das rs232 protokol schickt? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Zweite Urgenz beim Hersteller. Leider noch keine Reaktion.

**Comment by all-solutions** [comment]
Ich habe mich eben mal mit den Daten Deines Debug und denen von meinem Hybriden als Vergleich auseinander gesetzt. Spannend, die fahren unterschiedliche Protokolle. Wir reden von dem hier:
![image](https://user-images.githubusercontent.com/17761850/233143153-3d0e3de1-a636-446e-8a5b-a2d0cbe4e2da.png)
UM-V3, richtig?
Deiner scheint irgendwie das PI41 zu sprechen (zumindest was QPIGS angeht), passt aber im QPIRI dann doch nicht. Meiner spricht PI30 PIP. 


> Zweite Urgenz beim Hersteller. Leider noch keine Reaktion.

MasterPower kommt aus Spanien... die brauchen immer etwas länger...

**Comment by softwarecrash** [comment]
support added  with  V1.1.0
