### ISSUE TITLE
Typo in der Configseite

### ISSUE THREAD

**Issue by ghost** [softwarecrash/Solar2MQTT-ESP8266#28]
**Describe the bug**
Wenn ich die Seite http://192.168.1.44/settings öffnen, dann hat der Button Configure die Beschriftung Cofigure
![Screenshot 2023-04-10 113854](https://user-images.githubusercontent.com/58141879/230876729-4f9f7d19-d057-4ffb-9bff-5eb5c82a9da7.png)

**Comment by softwarecrash** [comment]
wurde im dev korrigiert
