### ISSUE TITLE
Inverter USB hidraw Interface

### ISSUE THREAD

**Issue by babajun12** [softwarecrash/Solar2MQTT-ESP8266#29]
I wonder if somebody was able connecting the ESP8266 to the USB interface of the inverter.
My PIP2424MSE doesn´t provide a RS232 port, even not internal. On Linux, the inverter port is discovered as a HID device.

Connecting a USB cable from a WEMOS D1 to the inverter didn´t work, at least no values are shown (only 0) on the Solar2MQTT.

Not sure if the onboard ESP-UART0 -> CH340 -> USB cable -> InverterPort could work at all?

**Comment by derLoosi** [comment]
Hey,
i am not sure if a complete usb interface including a driver is needed for that but i would think so.

i think the inverter is doing something like this on the usb port:
https://www.pjrc.com/teensy/rawhid.html
