### ISSUE TITLE
URL handling hivemq

### ISSUE THREAD

**Issue by MWagnerOE5AOO** [softwarecrash/Solar2MQTT-ESP8266#30]
I had create a free account an hivemq for testing. I get from hivemq a url like "ee9b57c42a8f48abad2774fe5e90ba3b.s2.eu.hivemq.cloud" Inserting this URL in SolarMQTT causes in a URL cutoff. After click Save setting the URL in the field is "ee9b57c42a8f48abad2774fe5e90ba3". It seems that no more than 32 chars are possible.

**Comment by all-solutions** [comment]
This has to do with the memory architecture. To fix this, the complete memory allocation must be changed. It was never intended to manage such long URL's. Most users have a local broker.
Will be adjusted with the next version jump if necessary. 
Until then you can solve it with a workaround: Find a URL-shortener service on the web. With that it should work.
