### ISSUE TITLE
[Bug]: Not reading W consumption values

### ISSUE THREAD

**Issue by Konycz** [softwarecrash/Solar2MQTT-ESP8266#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

Correct loading of inverter consumption values

### Screenshots / Fotos

From the beginning it worked for approx. 2 days, after that the consumption is loaded once in approx. 2 hours, charging the battery, etc. everything is fine
![obrazek](https://github.com/softwarecrash/Solar2MQTT/assets/15234512/78b9f8be-8fd9-4658-91d3-643a10c844e2)

### Version

0.5.1

### Relevant livejson output

```json
Solar In:
0V 0A 0W
Grid In:
1V 0Hz
AC Out:
228V 50Hz
AC Load:
0Va 0W 0%
Bus:
391V
Temperature:
342°C
Battery:
27.19V 100% 100%
SCC | IN | Out:
0V 0A 1A
Inverter Mode:
Battery
```

### What browsers are you seeing the problem on?

Firefox

**Comment by softwarecrash** [comment]
looks like your inverter use another sorting of data, your tempm value is the indicator

**Comment by Konycz** [comment]
![Screenshot 2023-07-19 at 16-55-32 Historie – Home Assistant](https://github.com/softwarecrash/Solar2MQTT/assets/15234512/2fd15cd8-f656-4de1-843b-b2f9dbf2a3c6)
This will certainly not be the temperature value.... because it correctly reads 90W here and that's what the display of the inverter shows me.
The value is prescribed to me in MQTT, but only approx. 1 time per hour

**Comment by softwarecrash** [comment]
your inverter send the data in the wrong order, you can actual nothing do.
i work on a complete new version but that need a lot of time

**Comment by Konycz** [comment]
But according to the display of the inverter, the consumption is 89-92W and this is not shown anywhere. And if by chance it shows the correct value there, at that moment the load of the converter in percentage is also shown (which also shows correctly), but only for a moment and then again on both the value is 0

And when will you release it approximately with the completion time of the new version?

**Comment by softwarecrash** [comment]
sure, thats missreading of the inverter data, what for model you have?

i dont have a timeline ore something, its a hobby and i work on other projects too

**Comment by Konycz** [comment]
https://vi.aliexpress.com/item/1005003340956819.html?spm=a2g0o.order_list.order_list_main.46.6fff18020dsd74&gatewayAdapt=glo2vnm

**Comment by softwarecrash** [comment]
check with the watchpower software and a com-usb cable to communicate, when this work, enable debug output on the software and post the log files here

**Comment by Konycz** [comment]
OK

**Comment by Konycz** [comment]
and where is the debug mode set in that program?
