### ISSUE TITLE
PCM - Data in wrong order

### ISSUE THREAD

**Issue by ian-tait** [softwarecrash/Solar2MQTT-ESP8266#4]
Hi Rocky,

I'm here because of your message on "daromer2".
You were right this fork has given me some results but they seem to be in the wrong order.

I have set the type to PCM
<img width="280" alt="Screenshot 2021-03-28 at 19 31 02" src="https://user-images.githubusercontent.com/22379332/112763428-4f4e6380-8ffc-11eb-999f-42b8b85e2b42.png">

Is it a case of just moving some of the variables around or have I messed something up?

**Comment by ian-tait** [comment]
<img width="302" alt="Screenshot 2021-03-28 at 19 35 47" src="https://user-images.githubusercontent.com/22379332/112763552-d3a0e680-8ffc-11eb-8e7a-0c51080167e8.png">

**Comment by softwarecrash** [comment]
hey, i working actual an the pip / pcm. yes just sort the variables in the inverter.cpp

at the moment its a bit buggy with the select of pcm / pip, i must reorganize it

but bevor, take the debug files from watchpower, there you can see of what for command your inverter answer and the order of data, please share this, so i can eventualy make a more dynamic thing.
