### ISSUE TITLE
[Bug]: PV-Volt falscher Wert, PV-Volt and PV-A ohne Nachkommastelle

### ISSUE THREAD

**Issue by AndyMuc72** [softwarecrash/Solar2MQTT-ESP8266#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

1. PV-Volt wird falsch angezeigt.
2. PV-Volt und PV-A haben keine Nachkommastelle

Ich benutze einen Solar Wechselrichter EASun Inverter SMP5K.
Ich habe noch parallel einen EaSun iSolar SMV II mit 5KVA laufen und habe die Werte mit solpiplog verglichen und die richtigen Stellen gefunden. Ich kann die aktuellen Werte von PV-Volt überhaupt nicht finden.

Per Screenshot habe ich den MQTT-Output von Solar2Mqtt an den richtigen Stellen markiert.
Leider kann ich in den nächsten Wochen nicht mit LiveView nachschauen. Ich hoffe das hilft weiter. Der Fehler ist konsistent nachvollziebar und in QPIGS immer an der gleicher Position.

### Screenshots / Fotos

![grafik](https://github.com/softwarecrash/Solar2MQTT/assets/50426013/67721ae7-4483-4a8f-8ac7-a82ff9f877f3)

![grafik](https://github.com/softwarecrash/Solar2MQTT/assets/50426013/115f3b32-0dd6-44ee-9e1a-38db2165dc07)

### Version

0.5.1

### Relevant livejson output

```json
{"gridV":0,"gridHz":0,"acOutV":230.1,"acOutHz":50,"acOutVa":69,"acOutW":39,"acOutPercent":1,"busV":371,"heatSinkDegC":45,"battV":50.2,"battPercent":80,"battChargeA":17,"battDischargeA":0,"sccBattV":0,"solarV":20,"solarA":3,"solarW":1003,"iv_mode":"Battery","device_name":"EaSun2"}
```

### What browsers are you seeing the problem on?

no Issue with the Browser or WebUI

**Comment by softwarecrash** [comment]
hab es glaub gefunden. hier ein fix (passt nicht für die platinenversion, die müsste @all-solutions erst anpassen)
[solar2MQTT 0.5.1-1.zip](https://github.com/softwarecrash/Solar2MQTT/files/12206855/solar2MQTT.0.5.1-1.zip)

**Comment by AndyMuc72** [comment]
Ich habe das Update durchgeführt. 
Jetzt bekomme ich keine Daten mehr. Es steht überall nur noch 0.

Vorher hatte ich eine beta Version 0.5.2 b2 oder so und die gefixte Version ist die 0.5.1-1. Auch die verfügbare Version 0.5.1 geht nicht mehr.
Möglicherweise wurde mein Wechselrichter erst in der 0.5.2 eingefügt?
Hättest du eine gefixte 0.5.2 beta?

**Comment by softwarecrash** [comment]
> Ich habe das Update durchgeführt. Jetzt bekomme ich keine Daten mehr. Es steht überall nur noch 0.
> 
> Vorher hatte ich eine beta Version 0.5.2 b2 oder so und die gefixte Version ist die 0.5.1-1. Auch die verfügbare Version 0.5.1 geht nicht mehr. Möglicherweise wurde mein Wechselrichter erst in der 0.5.2 eingefügt? Hättest du eine gefixte 0.5.2 beta?

hast du ein fertig PCB?

**Comment by AndyMuc72** [comment]
ja

**Comment by AndyMuc72** [comment]
komplett gekauft

**Comment by softwarecrash** [comment]
> ja

hab doch dazu geschrieben das der fix nicht mit den platinen kompatibel ist, das muss @all-solutions erst einpflegen, da musst du auf ihn warten. 
die PCB brauchen im moment noch eine angepasste version, die haupt version von hier bekommt das  erst im finalen rewrite

**Comment by AndyMuc72** [comment]
ach shit, überlesen, woher bekomme ich meine alte Version?

**Comment by softwarecrash** [comment]
> ach shit, überlesen, woher bekomme ich meine alte Version?

auch von ihm, er ist sicher später abends mal online, ggf kann er dir eine gefixte version bereitstellen

**Comment by AndyMuc72** [comment]
ok, danke. vermutlich über discord dann?

**Comment by softwarecrash** [comment]
> ok, danke. vermutlich über discord dann?

entweder dort oder hier, jenachdem wo er zuerst reinschaut
