### ISSUE TITLE
[FEATURE] Supply to UK

### ISSUE THREAD

**Issue by pmknowles** [softwarecrash/Solar2MQTT-ESP8266#41]
### Is your feature request related to a problem? Please describe

I think this might work with the EDECOA hybrid charger/inverter.

Rather than compile and flash I though I'd just buy the module. all-soutions.store doesn't seem to ship to the UK though.

### Describe the solution you'd like

Be able to buy from the UK

### Describe alternatives you've considered

A description on how to flash. Do I use platform.io or Arduino?

**Comment by softwarecrash** [comment]
Shipping to the UK is not possible because we cannot provide the papers required by customs.

flash it with tasmotizer or other tool.
all other information you find in the readme.
