### ISSUE TITLE
[Bug]:  does not hand in data,but it mqtt accession signals it

### ISSUE THREAD

**Issue by zsolti80** [softwarecrash/Solar2MQTT-ESP8266#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Other (please write your hardware in 'What happened?')

### What happened?

Onto ready one was tackling I use a supply:
https://all-solutions.store/de/shop/solar2mqtt-set/?fbclid=IwAR3cGeClP7fJlM98zeJZKsQ3pgoEdsneDGYULCUFgtfJaek6UM9SHP44Jzw

Does not work well, it mqtt contact good, but does not show data on the web application surface. Once good, restarted later not good.
The apparatus signals it how was attached, but does not send data. But is when works and sends it. But I do not see data again now!
My inverter: Qoltec 53886 Watchpower application and wifi added to him an apparatus works.

### Screenshots / Fotos

![mqtt2solar](https://github.com/softwarecrash/Solar2MQTT/assets/97821482/6b717b24-80e9-41b5-a3b9-73a33ffbd472)

### Version

1.x.x and above

### Relevant livejson output

```json
{"EspData":{"Device_name":"Solar2MQTT","ESP_VCC":2.981,"Version":"1.0.0"},"DeviceData":{},"LiveData":{}}
```

### What browsers are you seeing the problem on?

Chrome

**Comment by all-solutions** [comment]
Can you please falsh the debug-version of the firmware and then open the WebSerial (button in settings page), let them a few seconds and then copy the text from WebSerial here.

**Comment by zsolti80** [comment]
[He]([url]([url](url))) works again!
But the data appear as an entity without an identifier.
How can I take these under the energy ear? How I shall see it the battery and inverter consumption?
![inverter entitások](https://github.com/softwarecrash/Solar2MQTT/assets/97821482/209fce77-3e0d-419e-baef-0fd3ad430b73)

**Comment by all-solutions** [comment]
You have to implement the datapoints manually in HA. A good example for this can be found in Daly2MQTT. Must then be adapted to Solar2MQTT accordingly.
[https://github.com/JoergOstertag/DALY-BMS-to-MQTT/tree/main/docs/iot-integration](https://github.com/JoergOstertag/DALY-BMS-to-MQTT/tree/main/docs/iot-integration)

**Comment by zsolti80** [comment]
I entered the data points in the configuration.yaml file.  I have attached a picture.  But these are entities without an identifier.  Because of this, I cannot enter the data under the energy tab.  I would like help with this.  How can I display the data as an entity?  What should I put in the configuration.yaml file?
![1694711139678](https://github.com/softwarecrash/Solar2MQTT/assets/97821482/a3ab7065-0341-49a8-81a7-15ba8ab4b3db)

**Comment by Jarnsen** [comment]
Hi,

here is an example for the configuration. Its for daly2mqtt, but the form is the same.

Watch at code2, After that you must use a Rieman helper. The Energy Dashboard accepts only energy entities no power entities.

https://github.com/Jarnsen/Config_Daly2MQTT
