### ISSUE TITLE
password length

### ISSUE THREAD

**Issue by sargus123** [softwarecrash/Solar2MQTT-ESP8266#5]
home assistant defaults to 64 characters. (somehow I can't get around it)
  You have 40 characters in the settings, it needs to be corrected.
without it, it is impossible to connect to the MQTT

Password:
Phohfa6ie4ea4ohchohp8chaiMoa7Ge6vej5ieth2phohyah1Aquohhahj9eicao

mqtt log :
1629120146: New connection from 192.168.22.175 on port 1883.
1629120146: Socket error on client <unknown>, disconnecting.

**Comment by softwarecrash** [comment]
Thanks i will Change it
