### ISSUE TITLE
A new working device!

### ISSUE THREAD

**Issue by ReiCarst** [softwarecrash/Solar2MQTT-ESP8266#50]
### What device are you using?

PowMr 1500W Solar Hybrid Wechselrichter 12V DC auf 220V/230V AC mit 80A MPPT Solarregler Max. PV-Eingang 450V

and

EDECOA EM-161A

I can´t which Firmware Version the above Hybrid Inverters use.... but both are sending MQTT Messages to IOBroker just fine.
Thanks to softwarecrash !!

**Comment by softwarecrash** [comment]
Thank you for the report
