### ISSUE TITLE
POW-HVM6.2M-48V

### ISSUE THREAD

**Issue by masterjrock** [softwarecrash/Solar2MQTT-ESP8266#58]
### What device are you using?

Working on my unit right now.
Inverter: PowMr POW-HVM6.2M-48V
Software: Solar2MQTT 1.1.1A2
Device: 
D1 Mini Pro
RS232 TTL converter

**Comment by masterjrock** [comment]
![chrome_TcInOxJVww](https://github.com/softwarecrash/Solar2MQTT/assets/16200539/143a73d9-1888-4963-833c-3b7b968584c6)

**Comment by softwarecrash** [comment]
thank you for the report
