### ISSUE TITLE
MPPSolar 5KVA 48v HST4048

### ISSUE THREAD

**Issue by andrewalerian** [softwarecrash/Solar2MQTT-ESP8266#60]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

Hallo, dieser Wechselrichter ist eine Version mit drei Ladereglern, diese werden auch über watchpower angezeigt und verwaltet. Leider zeigt mir solar2mqtt nur einen Laderegler (PV) über MQTT an, gibt es eine Möglichkeit diese auch zu erfassen?

English:
Hello, this inverter is a version with three charge controllers, these are also displayed and managed via watchpower. Unfortunately, solar2mqtt only shows me one charge controller (PV) via MQTT, is there a way to record these as well?

### Screenshots / Fotos

![image](https://github.com/softwarecrash/Solar2MQTT/assets/149377390/7ce7467a-d350-46e2-abf7-65c90fc3f113)

![image](https://github.com/softwarecrash/Solar2MQTT/assets/149377390/e1465675-03d0-4237-9688-e6efeeb46970)

### Version

1.x.x and above

### Relevant livejson output

```json
{"EspData":{"Device_name":"MPPSolar5kVA","ESP_VCC":2.993,"Wifi_RSSI":-68,"sw_version":"1.1.3","Free_Heap":23528,"HEAP_Fragmentation":10,"json_memory_usage":1079},"DeviceData":{"AC_in_rating_voltage":230,"AC_in_rating_current":21.7,"AC_out_rating_voltage":230,"AC_out_rating_frequency":50,"AC_out_rating_current":21.7,"AC_out_rating_apparent_power":5000,"AC_out_rating_active_power":4000,"Battery_rating_voltage":48,"Battery_re-charge_voltage":48,"Battery_under_voltage":47.6,"Battery_bulk_voltage":55.2,"Battery_float_voltage":55.2,"Battery_type":"User","Current_max_AC_charging_current":2,"Current_max_charging_current":70,"Input_voltage_range":"UPS","Output_source_priority":"SBU first","Charger_source_priority":"Only solar charging permitted","Parallel_max_num":6,"Machine_type":20,"Topology":"Transformerless","Output_mode":0,"Battery_re-discharge_voltage":52,"PV_OK_condition_for_parallel":0,"PV_power_balance":1,"Protocol_ID":"PI30"},"LiveData":{"AC_in_Voltage":234.9,"AC_in_Frequenz":49.9,"AC_out_Voltage":234.9,"AC_out_Frequenz":49.9,"AC_out_VA":1174,"AC_out_Watt":1127,"AC_out_percent":28,"Inverter_Bus_Voltage":403,"Battery_Voltage":50.3,"Battery_Charge_Current":0,"Battery_Percent":25,"Inverter_Bus_Temperature":46,"PV_Input_Current":0,"PV_Input_Voltage":0,"Battery_SCC_Volt":0,"Battery_Discharge_Current":0,"Status_Flag":10000,"Battery_voltage_offset_fans_on":0,"EEPROM_Version":0,"PV_Charging_Power":0,"Device_Status":10,"Battery_Load":0,"PV_Input_Power":0,"Inverter_Operation_Mode":"Line"}}
```

### What browsers are you seeing the problem on?

no Issue with the Browser or WebUI

**Comment by softwarecrash** [comment]
aktuell gibt es nur die möglichkeit einen anzuzeigen. mehrere sind noch nicht vollständig implementiert mangels testmöglichkeiten bzw geräten.
gern kannst du dich im discord melden falls du die entwicklung unterstützen möchtest mit deinen geräten
