### ISSUE TITLE
6.2KW Breckner model BK77729

### ISSUE THREAD

**Issue by gillone** [softwarecrash/Solar2MQTT-ESP8266#63]
### What device are you using?

6.2KW Breckner model BK77729 last firmware 1.1.4 - looks OK - just a couple of things wrong - reports it as VMII-NXPW5KW, also Output_source_priority = solar first but it's set on Utility first.
Thank you for a great firmware - it was easy to wire and install.

**Comment by softwarecrash** [comment]
Hello,
thank you for the report.
the VMII-NXPW5KW is the real model name.
so some device types send resorted data for some source types. i cant fix that actual
