### ISSUE TITLE
[Bug]: Why information from Inverter not showing up just one blink and missing

### ISSUE THREAD

**Issue by rkoczen** [softwarecrash/Solar2MQTT-ESP8266#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

Information from Inverter not showing up just for a moment and missing

### Screenshots / Fotos

![image](https://github.com/softwarecrash/Solar2MQTT/assets/12825764/c769c0bc-e96b-4e6c-a3cf-2ca74173b820)

### Steps To Reproduce

First version is showing data

### Version

1.x.x and above

### Relevant livejson output

```json
{"EspData":{"Device_name":"Solar2MQTT","ESP_VCC":3.032,"Wifi_RSSI":-65,"sw_version":"1.1.6_Dongle","Free_Heap":22416,"HEAP_Fragmentation":11,"json_memory_usage":259},"DeviceData":{},"LiveData":{}}
```

### What browsers are you seeing the problem on?

Chrome

**Comment by softwarecrash** [comment]
Hello,
What you mean with First Version Work? What for a First Version?
What for a dongle you use?
What for Inverter? Protocol?

Need more information about your Setup and at wich Point of Change it Stop working.

Edit: in your issue description you Point that you use a wemos d1 Mini... You have flashed the dongle Version, that mismatch.

**Comment by rkoczen** [comment]
- V0.5.1 
- wemos d1 mini
- easun smh 3k

with this version it works:)
yes i know about mismatch but i was try all versions :)

**Comment by softwarecrash** [comment]
Please read the Wiki, since V1.x.x the Connection to the ESP have changed.
With v1 the complete communication has rewriten, so i dont know exactly what going wrong.

So i need more information
Can you provide The debug Log from webserial and USB after checking and Change the wireing

**Comment by rkoczen** [comment]
ok i'll stay on old version because it is works:)
