### ISSUE TITLE
New working easun igrid sv iv 5.6 kW device

### ISSUE THREAD

**Issue by amorfius** [softwarecrash/Solar2MQTT-ESP8266#65]
### What device are you using?

Good afternoon, respect for your work.

I have a hybrid inverter easun igrid sv iv 5.6 kW (which can mix electricity) I can’t make an animation for it. 

sensor.solar2mqtt_pv_charging_power
sensor.solar2mqtt_ac_out_watt

![power card](https://github.com/softwarecrash/Solar2MQTT/assets/145350694/a682e3af-1443-4b95-8f05-3952deaf31e8)

AC(inverter&grid) input Watt
how to get data for the Power flow card plus and Home Asistant Energy card

AC(inverter&grid) input Watt or sensor.solar2mqtt_ac_out_watt - sensor.solar2mqtt_pv_charging_power

**Comment by amorfius** [comment]
approximately this is what you need 
![testt](https://github.com/softwarecrash/Solar2MQTT/assets/145350694/a5551225-5f4d-4bba-9637-5edbfea07942)

**Comment by softwarecrash** [comment]
Thank you for reporting a working Device.

**Comment by Jarnsen** [comment]
Some hybrid inverter does not provide charged and discharged energy sensors. But we can do this ourselves very quickly. Take a look in the daly2mqtt Wiki, there is your solution.
