### ISSUE TITLE
POWLAND 3KVA 2400w 24Vdc Off Grid

### ISSUE THREAD

**Issue by pauliusrut** [softwarecrash/Solar2MQTT-ESP8266#67]
### What device are you using?

A new working device!
Solar Power Inverter 40A MPPT Solar Charger and 30A AC Charger
On label Isolar SMH3K
![image](https://github.com/softwarecrash/Solar2MQTT/assets/118569159/f7c2f756-90cf-488d-b9b4-bd3d149286a2)

**Comment by pauliusrut** [comment]
FW:
![image](https://github.com/softwarecrash/Solar2MQTT/assets/118569159/c0bcf9dc-c6cd-487d-8a63-9a5a4b0951b3)
![image](https://github.com/softwarecrash/Solar2MQTT/assets/118569159/c0b6ee17-30ef-46d1-aeb6-15ca22446988)

**Comment by softwarecrash** [comment]
Thank you
