### ISSUE TITLE
Solar2mqtt auto discovery

### ISSUE THREAD

**Issue by darkazar** [softwarecrash/Solar2MQTT-ESP8266#68]
### A clear and concise description of what the problem is.

I have mosquito broker installed on HA and multiple devices connected. Ha discovery is enabled. 
When Solar2mqtt is connected to broker, mqtt explorer shows data but its not discovered in HA.  I think HA discovery option in Solar2mqtt is not working. I have tested with second instance of HA and result is the same, no discovery. 
But in Daly2mqtt that i have too, autodiscovery is working fine ...

![solar2mqtt](https://github.com/softwarecrash/Solar2MQTT/assets/114813235/d4bbcfda-3cf0-496a-8f81-7d1d21155f93)

![Screenshot_20240204_114827_Chrome](https://github.com/softwarecrash/Solar2MQTT/assets/114813235/a66ceb55-2fec-4df5-9d7c-7aae767bf10c)

**Comment by softwarecrash** [comment]
Looks like you get no data from your device, i see only the esp data.
please provide the esp-ip/livejson data.

please remove the data on the trigger input field, this is only for a datapoint to trigger the esp sending data instant

**Comment by darkazar** [comment]
Yes , i figured it out. I have broken max 3232. 
Solved. Thank You.
