### ISSUE TITLE
Node MCU support

### ISSUE THREAD

**Issue by dotumair** [softwarecrash/Solar2MQTT-ESP8266#69]
### A clear and concise description of what the problem is.

Hi, Thanks for this great library. How can I flash the bin file in my Node MCU or even Can I? 
What configs do I need to change to work with Node MCU.

**Comment by softwarecrash** [comment]
Node MCU is just a name, when it have a ESP8266 use the wemos d1 mini Firmware and follow up the  wiring in the wiki

**Comment by dotumair** [comment]
Thanks for your help
