### ISSUE TITLE
[HELP] ESP8266

### ISSUE THREAD

**Issue by sanatho** [softwarecrash/Solar2MQTT-ESP8266#71]
instead of using wemos d1 mini can I use an nodeMCU esp8266 (like the one in the photo)?
![51y7hu31PbL _AC_UF1000,1000_QL80_](https://github.com/softwarecrash/Solar2MQTT/assets/70145951/dc3e811e-29ad-4f2a-a9ce-26fdb060c16e)

**Comment by all-solutions** [comment]
Yes you can.

Flash the Wemos D1 Mini Firmware and follow the connection diagram for Wemos using the same GPIO's.
