### ISSUE TITLE
Temperature sensor reading

### ISSUE THREAD

**Issue by darkazar** [softwarecrash/Solar2MQTT-ESP8266#72]
### A clear and concise description of what the problem is.

I have read from easun 3kw 24v inveter temperatures above 500 celsius. 

### Additional context

![20240208_120027](https://github.com/softwarecrash/Solar2MQTT/assets/114813235/1c57fe1f-46ac-40b2-adc5-70a3c84f5d39)
![Screenshot_20240208_115947_Chrome](https://github.com/softwarecrash/Solar2MQTT/assets/114813235/69fccb52-781d-4237-ab7b-91b00c357250)

JSON:

{"EspData":{"Device_name":"Solar2MQTT","ESP_VCC":2.98,"Wifi_RSSI":-34,"sw_version":"1.1.6","Free_Heap":22992,"HEAP_Fragmentation":17,"json_memory_usage":1224},"DeviceData":{"AC_in_rating_voltage":230,"AC_in_rating_current":13,"AC_out_rating_voltage":230,"AC_out_rating_frequency":50,"AC_out_rating_current":13,"AC_out_rating_apparent_power":3000,"AC_out_rating_active_power":3000,"Battery_rating_voltage":24,"Battery_re-charge_voltage":23,"Battery_under_voltage":21,"Battery_bulk_voltage":29.2,"Battery_float_voltage":27,"Battery_type":"Flooded","Current_max_AC_charging_current":15,"Current_max_charging_current":20,"Input_voltage_range":"Appliance","Output_source_priority":"Solar first","Charger_source_priority":"Solar + Utility","Parallel_max_num":0,"Machine_type":"Off Grid","Topology":"Transformer","Output_mode":0,"Battery_re-discharge_voltage":27,"PV_OK_condition_for_parallel":0,"PV_power_balance":0,"Device_Model":"SP-3000","Protocol_ID":"PI30"},"LiveData":{"AC_in_Voltage":229,"AC_in_Frequenz":50,"AC_out_Voltage":0,"AC_out_Frequenz":0,"AC_out_VA":0,"AC_out_Watt":0,"AC_out_percent":0,"Inverter_Bus_Voltage":286,"Battery_Voltage":27,"Battery_Charge_Current":0,"Battery_Percent":100,"Inverter_Bus_Temperature":515,"PV_Input_Current":0,"PV_Input_Voltage":0,"Battery_SCC_Volt":0,"Battery_Discharge_Current":0,"Status_Flag":1.00011008e7,"Battery_voltage_offset_fans_on":0,"EEPROM_Version":3,"PV_Charging_Power":0,"Device_Status":100,"Battery_Load":0,"PV_Input_Power":0,"Inverter_Operation_Mode":"Standby","PV_generation_sum":0,"PV_generation_year":0,"PV_generation_month":0,"PV_generation_day":0,"AC_in_generation_sum":0,"AC_in_generation_year":0,"AC_in_generation_month":0,"AC_in_generation_day":0}}

**Comment by softwarecrash** [comment]
Hello,
Your Inverter is one of These devices that send the Temperature Not as Celsius value.
Badly it send it as measured Differential voltage, there is No way to get this Temperature as correct Celsius value
