### ISSUE TITLE
New working device: EDECOA EM-304A

### ISSUE THREAD

**Issue by alessiocavalieri** [softwarecrash/Solar2MQTT-ESP8266#73]
### What device are you using?

A new working device!

Make: EDECOA 
Model: EM-304A

Sold on Amazon: https://www.amazon.it/EDECOA-48v-3000w-MPPT-55A/dp/B0BS16CCPN

or eBay

Firmware version

QVFW: Main CPU Firmware version inquiry 

VERFW:000SR.54

QVFW2: Another CPU Firmware version inquiry

N/A

**Comment by softwarecrash** [comment]
Thank your for the report
