### ISSUE TITLE
New working device

### ISSUE THREAD

**Issue by negronoir** [softwarecrash/Solar2MQTT-ESP8266#78]
### What device are you using?

Inverter: Axpert MKS IV 5.6K-48V

Inverter firm:
-Main CPU: 00074.01
-Secondary CPU: 00030.00
-Wifi Module: 3.1.1.0

Protocol detected: PI30

Solar2MQTT: V1.1.6

P.S. Solar2MQTT detects an older model MKS2-5600. This newer inverter has some more datapoints which are not managed by actual templates so they are not shown at HA integration.

**Comment by softwarecrash** [comment]
hello,
the data `MKS2-5600` is from your device, not from a detection, so the brander axpert just modify the modelnumber to IV and ordered a bit of modification from the producer. the core controller is an MKS2-5600 board

there is not template for datapoints, its dynamicly. so without the communication protocol from your device its not posible to try implement the new ones

**Comment by negronoir** [comment]
Hello

Ok, I understand. 

From Watchpower App I can see more live values due to the protocol. e.g.: The inverter is internally scheduled to change CSP at 01:00 a.m. from "Only Solar Charging allowed" to "Solar + Utility". At WatchPower I can see this change navigating in History. But Solar2MQTT never changes and always shows "Only Solar Charging allowed". My feeling is that in CSP menu "Only Solar Charging allowed" is set and this is which Solar2MQTT shows. But the temporary change due to the internal inverter scheduler is not decoded.

If you like, I can try to sniff serial data to get an updated protocol

Thanks!

**Comment by softwarecrash** [comment]
Solar2mqtt never Set anything by itself, the data e.x. "solar only" comes from your Inverter as a value Like 1 or 2 and is only rewriten for your to readable values and when changed Data from the devices comes, solar2mqtt will Show it, for unkown states it Show you the raw Data without rewrite.
When watchpower show it, please Check the different protocols in the repo, i never read about CSP.
Or ask your seller for the communication protocol.

Not needet to sniff the serial communication, you can enabled debug in watchpower (right click on the taskbar watchpower Icon and select debug) and then it record all for you, record it around the time when it Changes, ZIP the whole debug Files and Upload it here
