### ISSUE TITLE
Solar2MQTT V0.5.1 WORK, V1.1.6 NO

### ISSUE THREAD

**Issue by Konycz** [softwarecrash/Solar2MQTT-ESP8266#80]
### A clear and concise description of what the problem is.

Hi, I'm running Solar2MQTT V0.5.1 on my D1 mini and everything works, but as soon as I install the latest version 1.1.6, the device doesn't tell me the values from the inverter
![Screenshot 2024-03-24 at 11-20-01 Solar 2 MQTT](https://github.com/softwarecrash/Solar2MQTT/assets/15234512/a2277938-1bff-4764-874f-611b0ad337a1)
![Snímek obrazovky 2024-03-24 112142](https://github.com/softwarecrash/Solar2MQTT/assets/15234512/be46bd55-df8a-4760-827a-ac6f815cc95b)

**Comment by Konycz** [comment]
{
  "EspData": {
    "Device_name": "Solar2MQTT",
    "ESP_VCC": 3.013,
    "Wifi_RSSI": -46,
    "sw_version": "1.1.6_debug d1_mini Dec 30 2023 15:05:55",
    "Free_Heap": 24320,
    "HEAP_Fragmentation": 3,
    "json_memory_usage": 225,
    "json_capacity": 2048,
    "runtime": 9,
    "ws_clients": 0
  },
  "DeviceData": {},
  "LiveData": {}
}

**Comment by Konycz** [comment]
EASUN POWER 3KW 230VAC 24V Soalr Inverter 50Hz 60Hz 3000VA PWM 70A Pure Sine Wave Charge Current Inversor With Battery Charge

**Comment by rabeno** [comment]
Hi,
From the release page (https://github.com/softwarecrash/Solar2MQTT/releases) it seems that from version 1.0 there was a wiring change, so 1st thing to do is to check if your wiring is correct according to the wiring diagram (https://github.com/softwarecrash/Solar2MQTT/wiki/Wiring-Diagram). Hope this helps

**Comment by Konycz** [comment]
yes, you were right, thank you very much, but it displays the temperature quite strangely
![Screenshot 2024-03-24 at 17-29-57 Solar2MQTT](https://github.com/softwarecrash/Solar2MQTT/assets/15234512/91ae3e34-02b2-4ff4-ac14-d4b42e2f8890)

**Comment by rabeno** [comment]
Yes, I have the same problem, but according to this (https://github.com/softwarecrash/Solar2MQTT/issues/72#issuecomment-1935013899), there is nothing to do, since this software cannot translate the numeric value to real temperature.

**Comment by rabeno** [comment]
BTW, I have been investigating this issue myself, and according to the protocol description, the value of the temperature being displayed by this firmware should be divided by 10 in order to get the real temperature in Celsius. In your case, the real temp is 58.2

**Comment by softwarecrash** [comment]
hello,
yes with V1.x a new wireing is needed

great point that the temp value divide is correct, i will check to implement a little routine that check if the value large over 200 or so it will be divide by 10, thank you
