### ISSUE TITLE
EASUN POWER SMG-II-3.6K-WIFI

### ISSUE THREAD

**Issue by Camposmansi** [softwarecrash/Solar2MQTT-ESP8266#81]
### A clear and concise description of what the problem is.

I have this inverter and it does not work, what is needed so that it can be included? I am asking the manufacturer for the protocol

Thank you so much

**Comment by softwarecrash** [comment]
Hello,
Work your Inverter with watchpower or Solarpower Software (PC)? Please Check this with your Manual or seller

**Comment by Camposmansi** [comment]
I couldn't get it to work.

Work with a WiFi module for example: 
![EASUN-M-dulo-WiFi-con-soluci-n-de-monitoreo-remoto-RS232-dispósito-inal-mbrico- for-investor](https://github.com/softwarecrash/Solar2MQTT/assets/9553844/bc39ad75-7355-4db4-bc2b-6098e252575d)


Use the dessmonitor website or the SmartESS APP

**Comment by softwarecrash** [comment]
That was Not the question.

Sure that your wireing and other things works well?

**Comment by Camposmansi** [comment]
> That was Not the question.
> 
> Sure that your wireing and other things works well?

Yes, I have tried with 2 different TTL MAX, I have asked EASUN about the Protocol, I attached it, to see if it can come.
[SMG-RS232 Communication Protocol V1.0(1).pdf](https://github.com/softwarecrash/Solar2MQTT/files/14785967/SMG-RS232.Communication.Protocol.V1.0.1.pdf)

**Comment by softwarecrash** [comment]
thank you, your device uses modbus as communication, this is not implemented at the moment, its on the ToDo list, but unknown when i find time to implement this communication form, its complete different from the PiXX protocols

**Comment by Camposmansi** [comment]
I cry :'( 

Thank you very much for everything, I will look forward to it.

**Comment by mihaigsm2003** [comment]
when i received one SMG inverter to repair will try do some software for that inverter

**Comment by vGubriienko** [comment]
Any updates about SMG II Invertors support? I could help coding/debug if you point me where I could start.

**Comment by softwarecrash** [comment]
Modbus is now integrated in pre Release, but we need the Registers.
@bigdigital need you here

**Comment by vGubriienko** [comment]
I've tried [V1.2.0-Pre3](https://github.com/softwarecrash/Solar2MQTT/releases/tag/V1.2.0-Pre3) and get next logs, does it OK?
```
[WebSerial] Connecting...
[WebSerial] Connected...
[C:   QPI][CR:    0][CC:    0][L:   3]

QPI:		NAK (Length: 3)

[C: ^P005PI][CR:    0][CC:    0][L:   3]

^P005PI:		NAK (Length: 3)

Try Autodetect Protocol

[C:   QPI][CR:    0][CC:    0][L:   3]

QPI:		NAK (Length: 3)

[C: ^P005PI][CR:    0][CC:    0][L:   3]

^P005PI:		NAK (Length: 3)

Try Autodetect Protocol

[C:   QPI][CR:    0][CC:    0][L:   3]

QPI:		NAK (Length: 3)

[C: ^P005PI][CR:    0][CC:    0][L:   3]

^P005PI:		NAK (Length: 3)

Try Autodetect Modbus device

Response Timed Out

Response Timed Out

Time-out

Request failed!

Response Timed Out

Response Timed Out

Time-out

Request failed!

Response Timed Out

Response Timed Out

Time-out

Request failed!

Response Timed Out

Response Timed Out

Time-out

Request failed!

----------------- End Autodetect -----------------

ProzessData P:0 C:0
ProzessData P:0 C:0

```

**Comment by softwarecrash** [comment]
no thats not ok, it tells it cant get data
