### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by mihaigsm2003** [softwarecrash/Solar2MQTT-ESP8266#9]
Hi,
i try bin file, work ok (problem if not write PIP) but i need to modify some data, place direct MQTT data to script but i get error compilling using arduino IDE:

Arduino: 1.8.13 (Windows 7), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from c:\users\user\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed\xtensa-lx106-elf\include\assert.h:10,

                 from c:\users\user\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed\xtensa-lx106-elf\include\sys\reent.h:503,

                 from c:\users\user\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed\xtensa-lx106-elf\include\stdlib.h:18,

                 from c:\users\user\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed\xtensa-lx106-elf\include\c++\10.3.0\cstdlib:75,

                 from c:\users\user\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed\xtensa-lx106-elf\include\c++\10.3.0\stdlib.h:36,

                 from C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\cores\esp8266/Arduino.h:27,

                 from sketch\src.ino.cpp:1:

C:\Users\user\Documents\Arduino\libraries\WhareHauoraWiFiManager/WiFiManager.h:25:24: error: 'const char HTTP_HEAD []' redeclared as different kind of entity

   25 | const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";

      |                        ^~~~~~~

In file included from C:\Users\user\Documents\Arduino\libraries\WhareHauoraWiFiManager/WiFiManager.h:17,

                 from C:\Users\user\Desktop\arduino\solar\Solar2MQTT-master\Solar2MQTT-master\src\src.ino:10:

C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:39: note: previous declaration 'HTTPMethod HTTP_HEAD'

   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

      |                                       ^~~~~~~~~

C:\Users\user\Desktop\arduino\solar\Solar2MQTT-master\Solar2MQTT-master\src\src.ino: In lambda function:

src:190:47: error: 'sendHTMLmain' was not declared in this scope

  190 |                 server.send(200, "text/html", sendHTMLmain());

      |                                               ^~~~~~~~~~~~

C:\Users\user\Desktop\arduino\solar\Solar2MQTT-master\Solar2MQTT-master\src\src.ino: In lambda function:

src:204:47: error: 'sendHTMLconfirmReset' was not declared in this scope

  204 |                 server.send(200, "text/html", sendHTMLconfirmReset());

      |                                               ^~~~~~~~~~~~~~~~~~~~

C:\Users\user\Desktop\arduino\solar\Solar2MQTT-master\Solar2MQTT-master\src\src.ino: In lambda function:

src:220:47: error: 'sendHTMLsettings' was not declared in this scope

  220 |                 server.send(200, "text/html", sendHTMLsettings());

      |                                               ^~~~~~~~~~~~~~~~

C:\Users\user\Desktop\arduino\solar\Solar2MQTT-master\Solar2MQTT-master\src\src.ino: In lambda function:

src:226:47: error: 'sendHTMLsettingsEdit' was not declared in this scope

  226 |                 server.send(200, "text/html", sendHTMLsettingsEdit());

      |                                               ^~~~~~~~~~~~~~~~~~~~

exit status 1

'sendHTMLmain' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by softwarecrash** [comment]
try to compile it with VScode-Platformio
