### ISSUE TITLE
Master Power MF-OME-UM5KV4 

### ISSUE THREAD

**Issue by pkmaxl** [softwarecrash/Solar2MQTT-ESP8266#91]
### What device are you using?

A new working device!
MQTT reading: Device_Model VMIII-5600
Main CPU firmware: 0006.1.01
Secondary CPU firmware version: 00122.14
Thank you very much for your great work!
Yours Peter from Austria

**Comment by softwarecrash** [comment]
thank you for the report, it has ben added
