### ISSUE TITLE
New working device

### ISSUE THREAD

**Issue by Poerk** [softwarecrash/Solar2MQTT-ESP8266#96]
### What device are you using?

A new working device!
EDECOA EM-402A (4.2KVA 24V)

one sidenote: The smallest number for 'solar curent' seems to be "1A" even when the current is a few mA.
![image](https://github.com/softwarecrash/Solar2MQTT/assets/11649100/91330613-f576-4bd5-b73e-f83fb5d7feeb)

**Comment by softwarecrash** [comment]
thank you

**Comment by Lota23** [comment]
Hello, how is it connected. It doesn't work for me
Greeting
Lorenz

**Comment by RucioLoco** [comment]
Hi, I am having the same issue as Lota23.

My wiring is just as in DIY by Jarnsen youtube tutorial but I do not get data at all in the esp32 webui, also I am just guessing the "MQTT Server" is the IP for my Home Assistant?...
