### ISSUE TITLE
New working device

### ISSUE THREAD

**Issue by unimatrix-zeroo** [softwarecrash/Solar2MQTT-ESP8266#97]
### What device are you using?

easun smh ii 4,2kw new version is working

this one https://www.aliexpress.com/item/1005006474083383.html?spm=a2g0o.order_list.order_list_main.10.728f18025TLzBJ

**Comment by softwarecrash** [comment]
thank you for the report

**Comment by avenseElectro** [comment]
> ### What device are you using?
> easun smh ii 4,2kw new version is working
> 
> this one https://www.aliexpress.com/item/1005006474083383.html?spm=a2g0o.order_list.order_list_main.10.728f18025TLzBJ

What you did to mine isn't working
mine is that:  https://pt.aliexpress.com/item/1005006361049535.html?spm=a2g0o.order_list.order_list_main.5.8878caa422q7cp&gatewayAdapt=glo2bra
