### ISSUE TITLE
[FEATURE] <request for longer mqtt server text>

### ISSUE THREAD

**Issue by kamizama11** [softwarecrash/Solar2MQTT-ESP8266#99]
### Is your feature request related to a problem? Please describe

Need to add more character in mqtt server box to use cloud server

### Describe the solution you'd like

Add character count

### Describe alternatives you've considered

Thats it

**Comment by softwarecrash** [comment]
Try using URL shortener Like bit.ly 
Cloud Broker Most need encryption, the esp8266 doenst have enugh Power to manage  this
